import { groq } from "next-sanity";

// Light card-listing query for the project grid/deal (PRD Phase 5). Always
// dereferences category->title, never categoryName (Studio-only convenience
// field with no integrity guarantee — SCHEMA.md §3a). Uses previewImage, not
// heroImage — SCHEMA.md §3b documents previewImage as the field meant for
// grid/listing use; heroImage is reserved for the expanded project page
// (Phase 6/7), not fetched here.
export const projectListingQuery = groq`
  *[_type == "project"] | order(_createdAt desc) {
    _id,
    title,
    "slug": slug.current,
    category->{title, "slug": slug.current},
    previewImage{..., "url": asset->url},
    previewColor,
    projectColor,
    projectColorDark,
    ctaColor
  }
`;

// Reading-pane detail fetch, by _id, lazily requested when a card opens
// (lib/getProjects.ts's getProjectDetail) — the shared hero/overview shell's
// fields (§6) plus, conditionally, one of the 4 category-specific body
// blocks (§7/§9), gated on $category (already known to the caller from
// listing data — no extra category->title dereference needed here, unlike
// the reference's own allProjectsQuery). heroHeading/title aren't fetched:
// the fallback-to-title resolves client-side against the already-available
// listing-level title.
//
// Most image/video fields resolve to a plain URL string via asset->url
// (FRONTEND_INTEGRATION.md §3's documented convention for the ~150
// body-content fields) — only heroImage/closingImage above keep the
// full-object + url dual shape (one of the "5 exception fields").
export const projectDetailQuery = groq`
  *[_type == "project" && _id == $id][0]{
    heroSubheading,
    heroDescription,
    heroImage{..., "url": asset->url},
    projectTags,
    quickStats[]{title, value},
    tools[]->{title, "icon": icon.asset->url, color},
    liveLinks[]{text, subText, ctaIcon, url},
    closingImage{..., "url": asset->url},

    _type == "project" && $category == "Web Apps" => {
      "webApp_teaserImages": webApp_teaserImages[].asset->url,
      "webApp_teaserVideos": webApp_teaserVideos[].asset->url,
      "webApp_teaserVideoPosters": webApp_teaserVideoPosters[].asset->url,
      webApp_productContextHeading,
      webApp_productContext,
      "webApp_productContextImage": webApp_productContextImage.asset->url,
      "webApp_productContextVideo": webApp_productContextVideo.asset->url,
      "webApp_productContextVideoPoster": webApp_productContextVideoPoster.asset->url,
      webApp_probGoals[]{probGoalName, probGoalList},
      webApp_productStratHeading,
      webApp_productStratContent,
      webApp_uxHypothesisHeading,
      webApp_uxHypothesis,
      "webApp_uxHypothesisImage": webApp_uxHypothesisImage.asset->url,
      "webApp_uxHypothesisVideo": webApp_uxHypothesisVideo.asset->url,
      "webApp_uxHypothesisVideoPoster": webApp_uxHypothesisVideoPoster.asset->url,
      "webApp_initialDesignImages": webApp_initialDesignImages[].asset->url,
      "webApp_initialDesignVideos": webApp_initialDesignVideos[].asset->url,
      "webApp_initialDesignVideoPosters": webApp_initialDesignVideoPosters[].asset->url,
      webApp_prodScopeHeading,
      webApp_prodScope,
      webApp_prodScopeItems[]{itemTitle, itemRationale},
      webApp_designSectionHeading,
      webApp_designSectionText,
      "webApp_designSectionImages": webApp_designSectionImages[].asset->url,
      "webApp_designSectionVideos": webApp_designSectionVideos[].asset->url,
      "webApp_designSectionVideoPosters": webApp_designSectionVideoPosters[].asset->url,
      webApp_designSectionItems[]{
        itemName, itemPoints,
        "itemImage": itemImage.asset->url,
        "itemVideo": itemVideo.asset->url,
        "itemVideoPoster": itemVideoPoster.asset->url
      },
      webApp_devSectionHeading,
      webApp_devSectionText,
      webApp_devSectionItems[]{
        itemName, itemPoints,
        "itemImage": itemImage.asset->url,
        "itemVideo": itemVideo.asset->url,
        "itemVideoPoster": itemVideoPoster.asset->url
      },
      webApp_finishedProdHeading,
      webApp_finishedProdText,
      "webApp_finishedProdImages": webApp_finishedProdImages[].asset->url,
      "webApp_finishedProdVideos": webApp_finishedProdVideos[].asset->url,
      "webApp_finishedProdVideoPosters": webApp_finishedProdVideoPosters[].asset->url,
      webApp_outcomesSectionHeading,
      webApp_mainOutcomeHeading,
      webApp_mainOutcomeText,
      webApp_otherOutcomes[]{outcomeTitle, outcomeDescription},
      webApp_keyLearnHeading,
      webApp_keyLearnText,
      webApp_keyLearnList,
      "webApp_keyLearnImage": webApp_keyLearnImage.asset->url,
      "webApp_keyLearnVideo": webApp_keyLearnVideo.asset->url,
      "webApp_keyLearnVideoPoster": webApp_keyLearnVideoPoster.asset->url,
      webApp_whatWorkedHeading,
      webApp_whatWorkedText,
      webApp_whatWorkedList,
      "webApp_whatWorkedImage": webApp_whatWorkedImage.asset->url,
      "webApp_whatWorkedVideo": webApp_whatWorkedVideo.asset->url,
      "webApp_whatWorkedVideoPoster": webApp_whatWorkedVideoPoster.asset->url
    },

    _type == "project" && $category == "Websites" => {
      "website_teaserImages": website_teaserImages[].asset->url,
      "website_teaserVideos": website_teaserVideos[].asset->url,
      "website_teaserVideoPosters": website_teaserVideoPosters[].asset->url,
      website_businessContextHeading,
      website_businessContextContent,
      website_problemsIdentifiedHeading,
      website_problemsIdentified,
      "website_problemsIdentifiedImage": website_problemsIdentifiedImage.asset->url,
      "website_problemsIdentifiedVideo": website_problemsIdentifiedVideo.asset->url,
      "website_problemsIdentifiedVideoPoster": website_problemsIdentifiedVideoPoster.asset->url,
      website_designObjectivesHeading,
      website_designObjectives,
      "website_designObjectivesImage": website_designObjectivesImage.asset->url,
      "website_designObjectivesVideo": website_designObjectivesVideo.asset->url,
      "website_designObjectivesVideoPoster": website_designObjectivesVideoPoster.asset->url,
      website_marketContextHeading,
      website_marketContext,
      website_targetAudienceHeading,
      website_targetAudience[]{member, rationale},
      website_informationArcHeading,
      website_informationArcText,
      "website_informationArcImages": website_informationArcImages[].asset->url,
      "website_informationArcVideos": website_informationArcVideos[].asset->url,
      "website_informationArcVideoPosters": website_informationArcVideoPosters[].asset->url,
      website_uxStructureHeading,
      website_uxStructureText,
      website_uxStructureItems[]{
        structureName, structurePoints,
        "structureImage": structureImage.asset->url,
        "structureVideo": structureVideo.asset->url,
        "structureVideoPoster": structureVideoPoster.asset->url
      },
      website_visualDesignHeading,
      website_visualDesignText,
      "website_visualDesignImages": website_visualDesignImages[].asset->url,
      "website_visualDesignVideos": website_visualDesignVideos[].asset->url,
      "website_visualDesignVideoPosters": website_visualDesignVideoPosters[].asset->url,
      website_websiteBuildHeading,
      website_websiteBuildText,
      website_websiteBuildItems[]{
        buildItemName, buildItemPoints,
        "buildItemImage": buildItemImage.asset->url,
        "buildItemVideo": buildItemVideo.asset->url,
        "buildItemVideoPoster": buildItemVideoPoster.asset->url
      },
      "website_websiteBuildImages": website_websiteBuildImages[].asset->url,
      "website_websiteBuildVideos": website_websiteBuildVideos[].asset->url,
      "website_websiteBuildVideoPosters": website_websiteBuildVideoPosters[].asset->url,
      website_accessibilityHeading,
      website_accessibilityText,
      "website_accessibilityImages": website_accessibilityImages[].asset->url,
      "website_accessibilityVideos": website_accessibilityVideos[].asset->url,
      "website_accessibilityVideoPosters": website_accessibilityVideoPosters[].asset->url,
      website_preLaunchHeading,
      website_preLaunchChecks,
      "website_preLaunchImage": website_preLaunchImage.asset->url,
      "website_preLaunchVideo": website_preLaunchVideo.asset->url,
      "website_preLaunchVideoPoster": website_preLaunchVideoPoster.asset->url,
      website_outcomesSectionHeading,
      website_mainOutcomeHeading,
      website_mainOutcomeText,
      website_otherOutcomes[]{outcomeTitle, outcomeDescription},
      website_keyLearnHeading,
      website_keyLearnText,
      website_keyLearnList,
      "website_keyLearnImage": website_keyLearnImage.asset->url,
      "website_keyLearnVideo": website_keyLearnVideo.asset->url,
      "website_keyLearnVideoPoster": website_keyLearnVideoPoster.asset->url,
      website_whatWorkedHeading,
      website_whatWorkedText,
      website_whatWorkedList,
      "website_whatWorkedImage": website_whatWorkedImage.asset->url,
      "website_whatWorkedVideo": website_whatWorkedVideo.asset->url,
      "website_whatWorkedVideoPoster": website_whatWorkedVideoPoster.asset->url
    },

    _type == "project" && $category == "UX Case Studies" => {
      "platformImages": platformImages[].asset->url,
      "platformVideos": platformVideos[].asset->url,
      "platformVideoPosters": platformVideoPosters[].asset->url,
      projectRationaleHeading,
      projectRationale,
      "projectRationaleImage": projectRationaleImage.asset->url,
      "projectRationaleVideo": projectRationaleVideo.asset->url,
      "projectRationaleVideoPoster": projectRationaleVideoPoster.asset->url,
      researchSectionTitle,
      "researchSectionImage": researchSectionImage.asset->url,
      "researchSectionVideo": researchSectionVideo.asset->url,
      "researchSectionVideoPoster": researchSectionVideoPoster.asset->url,
      marketResearchHeading,
      marketResearchContent,
      "marketResearchVisual": marketResearchVisual.asset->url,
      "marketResearchVisualVideo": marketResearchVisualVideo.asset->url,
      "marketResearchVisualVideoPoster": marketResearchVisualVideoPoster.asset->url,
      competitiveAnalysisHeading,
      competitiveAnalysisIntro,
      competitors[]{
        competitorName, competitorType,
        "competitorImage": competitorImage.asset->url,
        "competitorVideo": competitorVideo.asset->url,
        "competitorVideoPoster": competitorVideoPoster.asset->url,
        competitorPros, competitorCons
      },
      opportunitiesHeading,
      opportunitiesList,
      "opportunitiesImage": opportunitiesImage.asset->url,
      "opportunitiesVideo": opportunitiesVideo.asset->url,
      "opportunitiesVideoPoster": opportunitiesVideoPoster.asset->url,
      userSurveyHeading,
      userSurveyIntro,
      "surveyCharts": surveyCharts[].asset->url,
      "surveyChartsVideo": surveyChartsVideo[].asset->url,
      "surveyChartsVideoPoster": surveyChartsVideoPoster[].asset->url,
      assumptionValidationHeading,
      assumptionValidation,
      "assumptionValidationImage": assumptionValidationImage.asset->url,
      "assumptionValidationVideo": assumptionValidationVideo.asset->url,
      "assumptionValidationVideoPoster": assumptionValidationVideoPoster.asset->url,
      keyInsightsHeading,
      keyInsights,
      opportunityText,
      personasHeading,
      personasIntro,
      "personas": personas[].asset->url,
      "personasVideo": personasVideo[].asset->url,
      "personasVideoPoster": personasVideoPoster[].asset->url,
      problemStatementHeading,
      problemStatement,
      designGoalsHeading,
      designGoals,
      ideationSectionTitle,
      "ideationSectionImage": ideationSectionImage.asset->url,
      "ideationSectionVideo": ideationSectionVideo.asset->url,
      "ideationSectionVideoPoster": ideationSectionVideoPoster.asset->url,
      userFlowHeading,
      userFlowDescription,
      "userFlowDiagrams": userFlowDiagrams[].asset->url,
      "userFlowDiagramsVideo": userFlowDiagramsVideo[].asset->url,
      "userFlowDiagramsVideoPoster": userFlowDiagramsVideoPoster[].asset->url,
      informationArchitectureHeading,
      informationArchitectureDescription,
      "informationArchitectureImage": informationArchitectureImage.asset->url,
      "informationArchitectureVideo": informationArchitectureVideo.asset->url,
      "informationArchitectureVideoPoster": informationArchitectureVideoPoster.asset->url,
      wireframesHeading,
      wireframesDescription,
      "wireframeImages": wireframeImages[].asset->url,
      "wireframeVideos": wireframeVideos[].asset->url,
      "wireframeVideoPosters": wireframeVideoPosters[].asset->url,
      visualDesignSectionTitle,
      "visualDesignSectionImage": visualDesignSectionImage.asset->url,
      "visualDesignSectionVideo": visualDesignSectionVideo.asset->url,
      "visualDesignSectionVideoPoster": visualDesignSectionVideoPoster.asset->url,
      styleGuideHeading,
      styleGuideDescription,
      "styleGuideImages": styleGuideImages[].asset->url,
      "styleGuideVideos": styleGuideVideos[].asset->url,
      "styleGuideVideoPosters": styleGuideVideoPosters[].asset->url,
      highFidelityHeading,
      highFidelityIntro,
      keyScreensList,
      "highFidelityMockups": highFidelityMockups[].asset->url,
      "highFidelityMockupsVideo": highFidelityMockupsVideo[].asset->url,
      "highFidelityMockupsVideoPoster": highFidelityMockupsVideoPoster[].asset->url,
      prototypeHeading,
      prototypeDescription,
      "prototypeImages": prototypeImages[].asset->url,
      "prototypeVideos": prototypeVideos[].asset->url,
      "prototypeVideoPosters": prototypeVideoPosters[].asset->url,
      prototypeNotes,
      validationHeading,
      validationDescription,
      validationMethodology,
      studyResultsHeading,
      studyResults,
      "studyResultsImage": studyResultsImage.asset->url,
      "studyResultsVideo": studyResultsVideo.asset->url,
      "studyResultsVideoPoster": studyResultsVideoPoster.asset->url,
      prototypeUpdateHeading,
      prototypeUpdates,
      "prototypeUpdatesImage": prototypeUpdatesImage.asset->url,
      "prototypeUpdatesVideo": prototypeUpdatesVideo.asset->url,
      "prototypeUpdatesVideoPoster": prototypeUpdatesVideoPoster.asset->url,
      accessibilityHeading,
      accessibilityConsiderations,
      "accessibilityMockup": accessibilityMockup.asset->url,
      "accessibilityMockupVideo": accessibilityMockupVideo.asset->url,
      "accessibilityMockupVideoPoster": accessibilityMockupVideoPoster.asset->url,
      finalThoughtsSectionHeading,
      "finalThoughtsSectionImage": finalThoughtsSectionImage.asset->url,
      "finalThoughtsSectionVideo": finalThoughtsSectionVideo.asset->url,
      "finalThoughtsSectionVideoPoster": finalThoughtsSectionVideoPoster.asset->url,
      finalResultsHeading,
      finalResultsText,
      expectedOutcomes,
      outcomesDisclaimer,
      keyLearningsHeading,
      keyLearnings,
      "keyLearningsImage": keyLearningsImage.asset->url,
      "keyLearningsVideo": keyLearningsVideo.asset->url,
      "keyLearningsVideoPoster": keyLearningsVideoPoster.asset->url,
      futureImprovementsHeading,
      futureImprovements[]{improvementTitle, improvementDescription},
      closingSummaryHeading,
      closingSummaryText
    },

    _type == "project" && $category == "Logos & Branding" => {
      "teaserImages": teaserImages[].asset->url,
      "teaserVideos": teaserVideos[].asset->url,
      "teaserVideoPosters": teaserVideoPosters[].asset->url,
      businessContextHeading,
      businessContextContent,
      problemsIdentifiedHeading,
      problemsIdentified,
      "problemsIdentifiedImage": problemsIdentifiedImage.asset->url,
      "problemsIdentifiedVideo": problemsIdentifiedVideo.asset->url,
      "problemsIdentifiedVideoPoster": problemsIdentifiedVideoPoster.asset->url,
      designObjectivesHeading,
      designObjectives,
      "designObjectivesImage": designObjectivesImage.asset->url,
      "designObjectivesVideo": designObjectivesVideo.asset->url,
      "designObjectivesVideoPoster": designObjectivesVideoPoster.asset->url,
      designApproachHeading,
      discoveryStrategyHeading,
      discoveryStrategy,
      designApproachMethods[]{approachTitle, approachDescription},
      firstCoreSectionHeading,
      firstCoreSectionText,
      firstCoreSectionList,
      "firstCoreLandscapeImages": firstCoreLandscapeImages[].asset->url,
      "firstCoreLandscapeVideos": firstCoreLandscapeVideos[].asset->url,
      "firstCoreLandscapeVideoPosters": firstCoreLandscapeVideoPosters[].asset->url,
      "firstCorePortraitImages": firstCorePortraitImages[].asset->url,
      "firstCorePortraitVideos": firstCorePortraitVideos[].asset->url,
      "firstCorePortraitVideoPosters": firstCorePortraitVideoPosters[].asset->url,
      secondCoreSectionHeading,
      secondCoreSectionText,
      secondCoreSectionList,
      "secondCoreLandscapeImages": secondCoreLandscapeImages[].asset->url,
      "secondCoreLandscapeVideos": secondCoreLandscapeVideos[].asset->url,
      "secondCoreLandscapeVideoPosters": secondCoreLandscapeVideoPosters[].asset->url,
      "secondCorePortraitImages": secondCorePortraitImages[].asset->url,
      "secondCorePortraitVideos": secondCorePortraitVideos[].asset->url,
      "secondCorePortraitVideoPosters": secondCorePortraitVideoPosters[].asset->url,
      thirdCoreSectionHeading,
      thirdCoreSectionText,
      thirdCoreSectionList,
      "thirdCoreLandscapeImages": thirdCoreLandscapeImages[].asset->url,
      "thirdCoreLandscapeVideos": thirdCoreLandscapeVideos[].asset->url,
      "thirdCoreLandscapeVideoPosters": thirdCoreLandscapeVideoPosters[].asset->url,
      "thirdCorePortraitImages": thirdCorePortraitImages[].asset->url,
      "thirdCorePortraitVideos": thirdCorePortraitVideos[].asset->url,
      "thirdCorePortraitVideoPosters": thirdCorePortraitVideoPosters[].asset->url,
      outcomesSectionHeading,
      mainOutcomeHeading,
      mainOutcomeText,
      otherOutcomes[]{outcomeTitle, outcomeDescription},
      keyLearnHeading,
      keyLearnText,
      keyLearnList,
      "keyLearnImage": keyLearnImage.asset->url,
      "keyLearnVideo": keyLearnVideo.asset->url,
      "keyLearnVideoPoster": keyLearnVideoPoster.asset->url,
      whatWorkedHeading,
      whatWorkedText,
      whatWorkedList,
      "whatWorkedImage": whatWorkedImage.asset->url,
      "whatWorkedVideo": whatWorkedVideo.asset->url,
      "whatWorkedVideoPoster": whatWorkedVideoPoster.asset->url
    }
  }
`;
